### ISSUE TITLE
No velocity sensitivity in Drumlabooh-multi

### ISSUE THREAD

**Issue by BMuXBeats** [psemiletov/drumlabooh#7]
In comparison to Drumlabooh the velocity sensitivity in Drumlabooh-multii doesn't work.  
I've reported the same behaviour in your issue list for Drumrox by the way.  
The "Ignore Velocity" checkbox i per default disabled and I didn't change it.

I've tested the .LV2 Plugin V 2.3.0 from the ARCH repository in Ardour 8.4 and Carla 2.5.8 as LV2 hosts.  
In both cases the same result.

I work under LINUX Manjaro 23.1.4 (Vulcan) /KDE-Plasma V 5.27.11

**Comment by psemiletov** [comment]
Thank you, I'll investigate it soon!

**Comment by psemiletov** [comment]
All fixed, thank you!

**Comment by BMuXBeats** [comment]
Hi Peter,

thank you so much for this tool and fixing the bug instantly. 👏🏼
It works flawless now. 💯👍🏻
